version: '3.8'

services:
  # Uptime Kuma - 一体化监控解决方案
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: cctv-uptime-kuma
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - uptime-kuma-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro  # 可选：Docker监控
    environment:
      - UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN=true
      - TZ=Asia/Shanghai
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.2'
          memory: 256M
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3001 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 可选：Nginx反向代理（如果需要HTTPS或域名访问）
  nginx:
    image: nginx:alpine
    container_name: cctv-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro  # SSL证书目录
    depends_on:
      - uptime-kuma
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M

volumes:
  uptime-kuma-data:
    driver: local

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16