global:
  scrape_interval: 30s
  evaluation_interval: 30s

rule_files:
  - 'alert.rules.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'alertmanager:9093'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]  # 使用http_2xx模块
    static_configs:
      - targets:
        - http://example.com # 示例目标，后续通过服务发现或配置添加实际设备
        # - 192.168.1.100 # 摄像头1
        # - 192.168.1.101 # 摄像头2
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115 # Blackbox exporter的地址

  - job_name: 'blackbox-ping'
    metrics_path: /probe
    params:
      module: [icmp] # 使用icmp模块
    static_configs:
      - targets:
        # - 192.168.1.200 # NVR
        # - 192.168.1.10  # 交换机1
        # - 192.168.1.11  # 交换机2
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115 # Blackbox exporter的地址

  - job_name: 'snmp'
    static_configs:
      - targets:
        # - 192.168.1.200 # NVR (SNMP)
        # - 192.168.1.10  # 交换机1 (SNMP)
        # - 192.168.1.11  # 交换机2 (SNMP)
    params:
      module: [if_mib] # 默认使用if_mib模块，可以根据设备类型创建更多模块
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp-exporter:9116 # SNMP exporter的地址

  - job_name: 'zabbix-sd'
    # Zabbix服务发现配置，可以使用 file_sd_configs 或 http_sd_configs
    # 这里使用 file_sd_configs 示例，需要一个脚本定期从Zabbix API获取设备列表并生成targets.json
    file_sd_configs:
      - files:
        - '/etc/prometheus/zabbix_targets.json'
        refresh_interval: 5m # 每5分钟刷新一次设备列表
    # 如果Zabbix中的设备也需要通过blackbox或snmp exporter监控，则需要相应的relabel_configs
    # 例如，如果zabbix_targets.json中的目标是IP地址，并且需要通过ping监控：
    # metrics_path: /probe
    # params:
    #   module: [icmp]
    # relabel_configs:
    #   - source_labels: [__address__]
    #     target_label: __param_target
    #   - source_labels: [__param_target]
    #     target_label: instance
    #   - target_label: __address__
    #     replacement: blackbox-exporter:9115

  # 可以添加更多job来监控其他服务或组件