apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy # Grafana后端代理访问Prometheus，避免浏览器跨域问题
    url: http://prometheus:9090 # Prometheus服务的内部地址
    jsonData:
      httpMethod: POST # 推荐使用POST以支持更长的查询
      exemplarTraceIdDestinations: # 示例：配置追踪ID目标
        - name: "trace_id"
          datasourceUid: "tempo" # 假设你有一个名为Tempo的追踪数据源
      # customQueryParameters: "timeout=30s"
    isDefault: true # 设置为默认数据源
    editable: true # 允许在Grafana UI中编辑
    version: 1

  - name: Zabbix # 示例：添加Zabbix作为数据源 (需要安装Grafana Zabbix插件)
    type: alexanderzobnin-zabbix-datasource
    access: proxy
    url: http://zabbix-web:8080/api_jsonrpc.php # Zabbix API地址
    jsonData:
      username: Admin # Zabbix用户名 (从环境变量或secrets管理更好)
      password: zabbix # Zabbix密码 (从环境变量或secrets管理更好)
      trends: true
      cacheTTL: 1m
    # secureJsonData:
    #   password: "${ZABBIX_API_PASSWORD}" # 更安全的方式是从环境变量注入
    editable: true
    version: 1

  # 如果需要，可以添加Alertmanager数据源 (需要安装相关插件)
  # - name: Alertmanager
  #   type: camptocamp-prometheus-alertmanager-datasource
  #   access: proxy
  #   url: http://alertmanager:9093
  #   jsonData:
  #     severity_critical_color: "rgba(212, 21, 21, 1)"
  #     severity_high_color: "rgba(242, 100, 30, 1)"
  #     severity_warning_color: "rgba(247, 176, 25, 1)"
  #     severity_info_color: "rgba(50, 172, 45, 1)"
  #   editable: true
  #   version: 1